USE [Senha]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SenhaGpt](
	[Id] [smallint] IDENTITY(1,1) NOT NULL,
	[PalavraChave] [varchar](50) NOT NULL,
	[SenhaGerada] [varchar](50) NOT NULL,
	[DataCadastro] [datetime] NULL,
	[DataVigencia] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
